apiVersion:  apps/v1

kind:  ReplicaSet

metadata:
  name: podrs
  labels:
    env: demo
    loc: on-prem-k8

spec:
  template:
    metadata:
      labels:
        env: demo
        loc: on-prem-k8
    spec:
      containers:
        - name: nginx-con
          image : nginx
          ports:
            - containerPort: 80
  replicas: 3    
  selector:
    matchLabels:
      env: demo

